sudo: false
language: python
python:
  -3.6
matrix:
  include: #Required for Python 3.7+
    - python: 3.7
      dist: xenial
    - python: 3.8
      dist: xenial
install:
  - pip install poetry
  - poetry install -vvv
script:
  - coverage run --source=test_mubu_login -m unittest discover
  - coverage report
